# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN --mount=type=cache,target=/root/.npm \
    npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the project
RUN npm run build

# Use a minimal Node.js runtime for the final image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the build output and package.json
COPY --from=builder /app/build ./build
COPY package.json ./

# Set the environment variable for the Firecrawl API key
ENV FIRECRAWL_API_KEY=your-api-key

# Expose the port the app runs on
EXPOSE 3000

# Command to run the server
CMD ["node", "build/index.js"]
